# netlify.toml
[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force HTTPS redirects
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Environment variables for build
[build.environment]
  NODE_VERSION = "20"
